const COLORS={"М1":"#e53935","М2":"#fb8c00","М3":"#2e7d32","М4":"#1e88e5","М5":"#8e24aa"};
const statusEl=document.getElementById("status"),filtersEl=document.getElementById("filters"),card=document.getElementById("card"),cardBody=document.getElementById("cardBody");
document.getElementById("closeCard").onclick=()=>card.classList.remove("show");
const active={},groups={}; Object.keys(COLORS).forEach(t=>{active[t]=true;groups[t]=[]});
let map=null;
function makeButton(team){const b=document.createElement("button");b.textContent=team;b.style.background=COLORS[team];b.onclick=()=>{active[team]=!active[team];b.classList.toggle("off",!active[team]);groups[team].forEach(pm=>active[team]?map.geoObjects.add(pm):map.geoObjects.remove(pm))};filtersEl.appendChild(b)}
Object.keys(COLORS).forEach(makeButton);
function showCard(item,coords,matched){cardBody.innerHTML='<h2>'+item.team+' · №'+item.n+' · '+item.district+'</h2><p><b>Адрес из списка:</b> '+item.address+'</p>'+(matched?'<p><b>Яндекс распознал:</b> '+matched+'</p>':'')+'<p><b>Координаты:</b> '+coords[0].toFixed(6)+', '+coords[1].toFixed(6)+'</p><div class="check ok">Точка поставлена Яндексом по полному адресу здания.</div>';card.classList.add("show")}
function loadV21(){return new Promise((resolve,reject)=>{if(window.ymaps)return resolve();const old=[...document.scripts].find(s=>s.src&&s.src.includes("api-maps.yandex.ru/v3/"));if(!old)return reject(new Error("Не найден загрузчик Яндекс Карт"));const s=document.createElement("script");s.src=old.src.replace("/v3/","/2.1/");s.onload=resolve;s.onerror=()=>reject(new Error("Не удалось загрузить Яндекс JS API 2.1"));document.head.appendChild(s)})}
async function geocodeItem(item){const key="mfc-yandex21:"+item.address;const cached=localStorage.getItem(key);if(cached){try{return JSON.parse(cached)}catch(e){}}return new Promise((resolve)=>{ymaps.geocode(item.address+", Россия",{results:1}).then(res=>{const obj=res.geoObjects.get(0);if(!obj)return resolve(null);const coords=obj.geometry.getCoordinates();const matched=obj.getAddressLine?obj.getAddressLine():obj.properties.get("text");const out={coords,matched};localStorage.setItem(key,JSON.stringify(out));resolve(out)},()=>resolve(null))})}
async function init(){try{statusEl.textContent="Загружаю Яндекс Карты…";await loadV21();await new Promise((res,rej)=>ymaps.ready(res,rej));map=new ymaps.Map("map",{center:[55.55,37.45],zoom:9,controls:["zoomControl"]},{suppressMapOpenBlock:true});
const bounds=[],failed=[];for(let i=0;i<MFC.length;i++){const [n,team,district,address]=MFC[i],item={n,team,district,address};statusEl.textContent="Сверяю адреса в Яндексе: "+(i+1)+" / 51";const g=await geocodeItem(item);if(g){const pm=new ymaps.Placemark(g.coords,{iconContent:String(n)},{preset:"islands#circleIcon",iconColor:COLORS[team]});pm.events.add("click",()=>showCard(item,g.coords,g.matched));groups[team].push(pm);map.geoObjects.add(pm);bounds.push(g.coords)}else failed.push(n);await new Promise(r=>setTimeout(r,120))}
if(bounds.length)map.setBounds(bounds,{checkZoomRange:true,zoomMargin:50});statusEl.textContent="На карте: "+bounds.length+" / 51"+(failed.length?" · не найдены № "+failed.join(", "):" · все адреса распознаны Яндексом")}catch(e){console.error(e);statusEl.textContent="Ошибка загрузки Яндекс Карт: "+(e.message||e)}}
init();